### PR TITLE
chore: Remove proxy-setup health check

### LINKED ISSUE #17: Eliminate remaining dependency on curl and jq in scripts/security-proxy-setup-checker.sh
This file
https://github.com/edgexfoundry/docker-edgex-consul/blob/master/scripts/security-proxy-setup-checker.sh

has a dependency on curl and jq.

This check should also be converted into a small static executable for completeness.

### LINKED ISSUE #27: Delete security-proxy-setup health check (not used)
No edgex microservice blocks on security-proxy-setup to be completed.  Consequently, the health  check can be removed.   This also means that https://github.com/edgexfoundry/docker-edgex-consul/issues/17 need to be fixed as well.

Affected files:

- https://github.com/edgexfoundry/docker-edgex-consul/blob/master/scripts/security-proxy-setup-checker.sh (remove)
- https://github.com/edgexfoundry/docker-edgex-consul/blob/master/config/secure/02-security-proxy-setup.json (remove)
- https://github.com/edgexfoundry/docker-edgex-consul/blob/master/Dockerfile  (remove curl and jq depdencencies)

cc @mkbhanda

### PR DESCRIPTION
**Pull request by bnevis-i**
There are no sevices dependent on security-proxy-setup
finishing. Remove the health check.

Closes #17 
Closes #27

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

### CODE REVIEW

**Comment by bnevis-i** [comment]
Schedule for Hanoi

**Comment by bnevis-i** [comment]
@jpwhitemn @tingyuz Can we unfreeze this one now that Geneva release is cut?

**Comment by tingyuz** [comment]
@bnevis-i  I removed the hold label so that we can work on it.

**Review by mkbhanda — APPROVED** [review]

**Review by lenny-goodell — APPROVED** [review]
LGTM

**Comment by lenny-goodell** [comment]
@bnevis-i Need to rebase...

**Comment by bnevis-i** [comment]
@lenny-intel Merged in master instead.  Make sure to squash marge it.

**Comment by bnevis-i** [comment]
Thank you, @lenny-intel !

**Pull request merged**
