### PR TITLE
consul-svc-healthy: use system jq if available (master)

### PR DESCRIPTION
**Pull request by anonymouse64**
Duplicate of #7 but for master/Geneva

### CODE REVIEW

**Comment by bnevis-i** [comment]
LGTM

**Comment by michaelestrin** [comment]
@anonymouse64 Rebase required (option to update not available to me via GitHub UI).

**Review by bnevis-i — DISMISSED** [review]

**Comment by anonymouse64** [comment]
Thanks, rebased

**Comment by michaelestrin** [comment]
recheck

**Review by bnevis-i — DISMISSED** [review]
LGTM (unofficial)

**Comment by bnevis-i** [comment]
This PR is languishing from inattention and lack of repository-level committers.

**Review by tingyuz — APPROVED** [review]

**Pull request merged**
