### PR TITLE
feat(security): Remove Vault's healthy check in Consul

### PR DESCRIPTION
**Pull request by jim-wang-yutsung**
With the Vault's backend being changed from consul to filesystem, Vault's healthy check now becomes superfluous.

The original automatically generated healthy check in Vault now is gone due to Vault's backend storage is not dependent on Consul any more.

This together with edgex-go's change shall remove the dependency of Vault from Consul.

Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/docker-edgex-consul/blob/master/.github/Contributing.md.

## What is the current behavior?

Vault's healthy check within Consul

## What is the new behavior?
No Vault's healthy check directly from Consul

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information
Related to https://github.com/edgexfoundry/edgex-go/issues/2882 
Also see PR: https://github.com/edgexfoundry/edgex-go/pull/2886

### CODE REVIEW

**Comment by jim-wang-yutsung** [comment]
@lenny-intel or @jpwhitemn or @bnevis-i  if you have the written permission please add @beaufrusetta, @bnevis-i, @lenny-intel, @hutchic as reviewers . This is for Ireland scope.    I don't have that permission. Thanks.

**Comment by beaufrusetta** [comment]
> @lenny-intel or @jpwhitemn or @bnevis-i if you have the written permission please add @beaufrusetta, @bnevis-i, @lenny-intel, @hutchic as reviewers . This is for Ireland scope. I don't have that permission. Thanks.

Yeah @lenny-intel - when do I become "git official" with EdgeX? 😆

**Review by bnevis-i — APPROVED** [review]

**Review by lenny-goodell — APPROVED** [review]
LGTM, moving to draft until ADR is approved

**Comment by jim-wang-yutsung** [comment]
@lenny-intel  could we also move this to PR ready?

**Review by hutchic — APPROVED** [review]

**Pull request merged**
